---
title: "Grand Analysis"
output:
  pdf_document: default
  html_document: default
---

---
title: "Grand Analysis"
output: html_document
---

### Upload Packages
```{r upload-packages, message=FALSE}
library(tidyverse)
```

### Load files
```{r load-files}
MetWit2DDmovement<-read.csv("MetWit2DDmovement.csv", header = TRUE)
MetWit2LDmovement<-read.csv("MetWit2LDmovement.csv", header = TRUE)
MetWit1DDmovement<-read.csv("MetWit1DDmovement.csv", header = TRUE)
MetWit1LDmovement<-read.csv("MetWit1LDmovement.csv", header = TRUE)
```

### Merge Data 2DD

```{r merge-data-2DD}
#remove the X column that counts number of rows
MetWit2DDmovement <- MetWit2DDmovement%>%
  select(-X)


#merge all columns into a single column
joined_MetWit2DD <- data.frame(unlist(MetWit2DDmovement))

joined_MetWit2DD <- joined_MetWit2DD%>%
  rename(movements=unlist.MetWit2DDmovement.)

#remove NA rows
joined_MetWit2DD <- na.omit(joined_MetWit2DD)

```

### Merge Data 1DD

```{r merge-data-1DD}
#remove the X column that counts number of rows
MetWit1DDmovement <- MetWit1DDmovement%>%
  select(-X)


#merge all columns into a single column
joined_MetWit1DD <- data.frame(unlist(MetWit1DDmovement))

joined_MetWit1DD <- joined_MetWit1DD%>%
  rename(movements=unlist.MetWit1DDmovement.)

#remove NA rows
joined_MetWit1DD <- na.omit(joined_MetWit1DD)

```

### Merge DD Data

```{r}
joined_MetWitDD <- rbind(joined_MetWit1DD, joined_MetWit2DD)
head(joined_MetWitDD)
```


### Merge Data 2LD

```{r merge-data-2LD}
#remove the X column that counts number of rows
MetWit2LDmovement <- MetWit2LDmovement%>%
  select(-X)


#merge all columns into a single column
joined_MetWit2LD <- data.frame(unlist(MetWit2LDmovement))

joined_MetWit2LD <- joined_MetWit2LD%>%
  rename(movements=unlist.MetWit2LDmovement.)

#remove NA rows
joined_MetWit2LD <- na.omit(joined_MetWit2LD)

```

### Merge Data 1LD

```{r merge-data-1LD}
#remove the X column that counts number of rows
MetWit1LDmovement <- MetWit1LDmovement%>%
  select(-X)


#merge all columns into a single column
joined_MetWit1LD <- data.frame(unlist(MetWit1LDmovement))

joined_MetWit1LD <- joined_MetWit1LD%>%
  rename(movements=unlist.MetWit1LDmovement.)

#remove NA rows
joined_MetWit1LD <- na.omit(joined_MetWit1LD)

```

### Merge LD Data

```{r}
joined_MetWitLD <- rbind(joined_MetWit1LD, joined_MetWit2LD)
head(joined_MetWitLD)
```

### ECDF for all DD data

```{r}
ggplot(data = joined_MetWitDD)+
  stat_ecdf(aes(movements))+
  labs(title = "MetWitDD ECDF", x = "Spider Movements", y = "% of Spiders")
```

### ECDF for all LD data

```{r}
ggplot(data = joined_MetWitLD)+
  stat_ecdf(aes(movements))+
  labs(title = "MetWitLD ECDF", x = "Spider Movements", y = "% of Spiders")
```

### ECDF both LD and DD

```{r}
ggplot()+
  stat_ecdf(data = joined_MetWitLD, aes(movements))+
  stat_ecdf(data = joined_MetWitDD, aes(movements), color = "red") +
  labs(title = "MetWit combined ECDF", x = "Spider Movements", y = "% of Spiders")
```


### Histogram for DD Data

```{r}
ggplot(data = joined_MetWitDD, aes(x = movements)) +
  geom_histogram(binwidth = 5) +
  geom_density(aes(y = ..density.. * 10000)) +
  labs(title = "MetWitDD Histogram", x = "Spider Movements", y = "Count")
  
hist(joined_MetWitDD$movements, breaks = 20, probability = TRUE)
lines(density(joined_MetWitDD$movements))
```

### Histogram for LD Data

```{r}
ggplot(data = joined_MetWitLD, aes(x = movements)) +
  geom_histogram(binwidth = 5) +
  geom_density(aes(y = ..density.. * 10000)) +
  labs(title = "MetWitLD Histogram", x = "Spider Movements", y = "Count")
  
hist(joined_MetWitLD$movements, breaks = 20, probability = TRUE)
lines(density(joined_MetWitLD$movements))

```































