---
title: "Simulation of Spider Movements"
author: "Alice Chen"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---
### Load Packages

```{r}
library(tidyverse)
```

### Load Data

```{r}
sample_data <- read.csv("MetWit2DD_movement_lengths.csv", header = TRUE)

joined_2DD <- read.csv("joined_MetWit2DD.csv", header=TRUE)
```
### Clean Data

```{r}
sample_data <- sample_data %>%
  rename(count = n,
         movement_length = movements)

joined_2DD %>%
  head()
```

### Creating Number Generator

```{r}
set.seed(2022)
moving_or_not <- rnorm(n = 120, mean = 0, sd = 1)
newdf <- as.data.frame(moving_or_not)

new_df <- newdf %>%
  mutate(state = ifelse(moving_or_not<0, 0, 1)) 
```

### Randomly generating values from joined_2DD

```{r}
training_joined2DD <- joined_2DD %>%
  slice_sample(prop = 1) 
training_joined2DD
```


### If state = 1, then pull from joined_2DD data a random run length

```{r find-run-lengths}
new_df %>%
  mutate(runtimes = ifelse(state == 1,
                           sample(training_joined2DD$movements, 1),
                           0)) 





```


